# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Lectura-Celda-de-carga-python\inicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inicio(object):
    def setupUi(self, Inicio):
        Inicio.setObjectName("Inicio")
        Inicio.resize(1045, 572)
        self.centralwidget = QtWidgets.QWidget(Inicio)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblPesoIndicador = QtWidgets.QLabel(self.frame)
        self.lblPesoIndicador.setGeometry(QtCore.QRect(20, 110, 341, 111))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lblPesoIndicador.setFont(font)
        self.lblPesoIndicador.setStyleSheet("")
        self.lblPesoIndicador.setObjectName("lblPesoIndicador")
        self.lblEstadoIndicador = QtWidgets.QLabel(self.frame)
        self.lblEstadoIndicador.setGeometry(QtCore.QRect(10, 10, 140, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEstadoIndicador.setFont(font)
        self.lblEstadoIndicador.setStyleSheet("")
        self.lblEstadoIndicador.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEstadoIndicador.setObjectName("lblEstadoIndicador")
        self.btn_restart = QtWidgets.QPushButton(self.frame)
        self.btn_restart.setGeometry(QtCore.QRect(840, 10, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_restart.setFont(font)
        self.btn_restart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_restart.setStyleSheet("#btn_restart {\n"
"    background-color: #F20000;\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #D10000;\n"
"    border-right: 1px solid #D10000;\n"
"    border-bottom: 5px solid #D10000;\n"
"}\n"
"\n"
"#btn_restart_adc:hover {\n"
"    background-color: #D13600\n"
"}\n"
"\n"
"#btn_restart_adc:pressed {\n"
"    background-color: #ED0000;\n"
"}\n"
"")
        self.btn_restart.setObjectName("btn_restart")
        self.lbl_valor_min = QtWidgets.QLabel(self.frame)
        self.lbl_valor_min.setGeometry(QtCore.QRect(600, 16, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_valor_min.setFont(font)
        self.lbl_valor_min.setStyleSheet("")
        self.lbl_valor_min.setObjectName("lbl_valor_min")
        self.lbl_valor_max = QtWidgets.QLabel(self.frame)
        self.lbl_valor_max.setGeometry(QtCore.QRect(600, 120, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_valor_max.setFont(font)
        self.lbl_valor_max.setStyleSheet("")
        self.lbl_valor_max.setObjectName("lbl_valor_max")
        self.lbltxtvmin = QtWidgets.QLabel(self.frame)
        self.lbltxtvmin.setGeometry(QtCore.QRect(512, 20, 70, 23))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbltxtvmin.setFont(font)
        self.lbltxtvmin.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltxtvmin.setObjectName("lbltxtvmin")
        self.lbltxtvmax = QtWidgets.QLabel(self.frame)
        self.lbltxtvmax.setGeometry(QtCore.QRect(510, 124, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbltxtvmax.setFont(font)
        self.lbltxtvmax.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltxtvmax.setObjectName("lbltxtvmax")
        self.btn_restart_cont = QtWidgets.QPushButton(self.frame)
        self.btn_restart_cont.setGeometry(QtCore.QRect(840, 100, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_restart_cont.setFont(font)
        self.btn_restart_cont.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_restart_cont.setStyleSheet("#btn_restart_cont {\n"
"    background-color: #FF8000;\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #D96D00;\n"
"    border-right: 1px solid #D96D00;\n"
"    border-bottom: 5px solid #D96D00;\n"
"    justify-content: center;\n"
"     align-items: center;\n"
"}\n"
"\n"
"#btn_restart_adc:hover {\n"
"    background-color: #EB7900;\n"
"}\n"
"\n"
"#btn_restart_adc:pressed {\n"
"    background-color: #FF8400;\n"
"}\n"
"")
        self.btn_restart_cont.setObjectName("btn_restart_cont")
        self.lbltxtmargen = QtWidgets.QLabel(self.frame)
        self.lbltxtmargen.setGeometry(QtCore.QRect(508, 180, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbltxtmargen.setFont(font)
        self.lbltxtmargen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltxtmargen.setObjectName("lbltxtmargen")
        self.lbl_margen = QtWidgets.QLabel(self.frame)
        self.lbl_margen.setGeometry(QtCore.QRect(640, 180, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_margen.setFont(font)
        self.lbl_margen.setStyleSheet("")
        self.lbl_margen.setObjectName("lbl_margen")
        self.lbl_peso_calibrado = QtWidgets.QLabel(self.frame)
        self.lbl_peso_calibrado.setGeometry(QtCore.QRect(20, 270, 331, 111))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbl_peso_calibrado.setFont(font)
        self.lbl_peso_calibrado.setStyleSheet("")
        self.lbl_peso_calibrado.setObjectName("lbl_peso_calibrado")
        self.txt_peso_real = QtWidgets.QLineEdit(self.frame)
        self.txt_peso_real.setGeometry(QtCore.QRect(750, 370, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_peso_real.setFont(font)
        self.txt_peso_real.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_peso_real.setAutoFillBackground(False)
        self.txt_peso_real.setStyleSheet("border-radius: 5px;\n"
"border: 2px solid #DDD;\n"
"background-color: rgb(255, 255, 255);")
        self.txt_peso_real.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_peso_real.setObjectName("txt_peso_real")
        self.btn_calibrar = QtWidgets.QPushButton(self.frame)
        self.btn_calibrar.setGeometry(QtCore.QRect(680, 440, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calibrar.setFont(font)
        self.btn_calibrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_calibrar.setStyleSheet("#btn_calibrar {\n"
"    background-color: #2F00ED;\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #2700C2;\n"
"    border-right: 1px solid #2700C2;\n"
"    border-bottom: 5px solid #2700C2;\n"
"}\n"
"\n"
"#btn_restart_adc:hover {\n"
"    background-color: #4D00F2;\n"
"}\n"
"\n"
"#btn_restart_adc:pressed {\n"
"    background-color: #4800E3;\n"
"}\n"
"")
        self.btn_calibrar.setObjectName("btn_calibrar")
        self.lbl_medio = QtWidgets.QLabel(self.frame)
        self.lbl_medio.setGeometry(QtCore.QRect(600, 70, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_medio.setFont(font)
        self.lbl_medio.setStyleSheet("")
        self.lbl_medio.setObjectName("lbl_medio")
        self.lbltxtmargen_2 = QtWidgets.QLabel(self.frame)
        self.lbltxtmargen_2.setGeometry(QtCore.QRect(514, 72, 70, 23))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbltxtmargen_2.setFont(font)
        self.lbltxtmargen_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltxtmargen_2.setObjectName("lbltxtmargen_2")
        self.lbltxDisplay_PesoReal = QtWidgets.QLabel(self.frame)
        self.lbltxDisplay_PesoReal.setGeometry(QtCore.QRect(720, 290, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbltxDisplay_PesoReal.setFont(font)
        self.lbltxDisplay_PesoReal.setStyleSheet("")
        self.lbltxDisplay_PesoReal.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltxDisplay_PesoReal.setObjectName("lbltxDisplay_PesoReal")
        self.btn_restart_adc = QtWidgets.QPushButton(self.frame)
        self.btn_restart_adc.setGeometry(QtCore.QRect(840, 190, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_restart_adc.setFont(font)
        self.btn_restart_adc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_restart_adc.setStyleSheet("#btn_restart_adc {\n"
"    background-color: #00D139;\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #089930;\n"
"    border-right: 1px solid #089930;\n"
"    border-bottom: 5px solid #089930;\n"
"}\n"
"\n"
"#btn_restart_adc:hover {\n"
"    background-color: #20E355;\n"
"}\n"
"\n"
"#btn_restart_adc:pressed {\n"
"    background-color: #14BC43;\n"
"}\n"
"")
        self.btn_restart_adc.setObjectName("btn_restart_adc")
        self.btn_mostrar_peso = QtWidgets.QPushButton(self.frame)
        self.btn_mostrar_peso.setGeometry(QtCore.QRect(830, 440, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_mostrar_peso.setFont(font)
        self.btn_mostrar_peso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mostrar_peso.setStyleSheet("#btn_mostrar_peso {\n"
"    background-color: #00D139;\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    border-left: 1px solid #089930;\n"
"    border-right: 1px solid #089930;\n"
"    border-bottom: 5px solid #089930;\n"
"}\n"
"\n"
"#btn_restart_adc:hover {\n"
"    background-color: #20E355;\n"
"}\n"
"\n"
"#btn_restart_adc:pressed {\n"
"    background-color: #14BC43;\n"
"}")
        self.btn_mostrar_peso.setObjectName("btn_mostrar_peso")
        self.combo_Port = QtWidgets.QComboBox(self.frame)
        self.combo_Port.setGeometry(QtCore.QRect(310, 14, 100, 22))
        self.combo_Port.setObjectName("combo_Port")
        self.lbl_port = QtWidgets.QLabel(self.frame)
        self.lbl_port.setGeometry(QtCore.QRect(180, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("AlphaMaleModern")
        font.setPointSize(14)
        self.lbl_port.setFont(font)
        self.lbl_port.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_port.setStyleSheet("")
        self.lbl_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_port.setObjectName("lbl_port")
        self.lbltxKG = QtWidgets.QLabel(self.frame)
        self.lbltxKG.setGeometry(QtCore.QRect(360, 290, 101, 71))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbltxKG.setFont(font)
        self.lbltxKG.setStyleSheet("")
        self.lbltxKG.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltxKG.setObjectName("lbltxKG")
        self.lblPesoIndicador.raise_()
        self.lblEstadoIndicador.raise_()
        self.btn_restart.raise_()
        self.lbl_valor_min.raise_()
        self.lbl_valor_max.raise_()
        self.lbltxtvmin.raise_()
        self.lbltxtvmax.raise_()
        self.lbltxtmargen.raise_()
        self.lbl_margen.raise_()
        self.lbl_peso_calibrado.raise_()
        self.txt_peso_real.raise_()
        self.btn_calibrar.raise_()
        self.lbl_medio.raise_()
        self.lbltxtmargen_2.raise_()
        self.lbltxDisplay_PesoReal.raise_()
        self.btn_restart_adc.raise_()
        self.btn_mostrar_peso.raise_()
        self.combo_Port.raise_()
        self.lbl_port.raise_()
        self.lbltxKG.raise_()
        self.btn_restart_cont.raise_()
        self.verticalLayout.addWidget(self.frame)
        Inicio.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Inicio)
        self.statusbar.setObjectName("statusbar")
        Inicio.setStatusBar(self.statusbar)

        self.retranslateUi(Inicio)
        QtCore.QMetaObject.connectSlotsByName(Inicio)

    def retranslateUi(self, Inicio):
        _translate = QtCore.QCoreApplication.translate
        Inicio.setWindowTitle(_translate("Inicio", "MainWindow"))
        self.lblPesoIndicador.setText(_translate("Inicio", "-------------"))
        self.lblEstadoIndicador.setText(_translate("Inicio", "Estado"))
        self.btn_restart.setText(_translate("Inicio", "REINICIAR CELDA"))
        self.lbl_valor_min.setText(_translate("Inicio", "0"))
        self.lbl_valor_max.setText(_translate("Inicio", "0"))
        self.lbltxtvmin.setText(_translate("Inicio", "MIN :"))
        self.lbltxtvmax.setText(_translate("Inicio", "MAX :"))
        self.btn_restart_cont.setText(_translate("Inicio", "REINICIAR VALORES\n"
"Min/Max"))
        self.lbltxtmargen.setText(_translate("Inicio", "MARGEN :"))
        self.lbl_margen.setText(_translate("Inicio", "- - - - - - -"))
        self.lbl_peso_calibrado.setText(_translate("Inicio", "-------------"))
        self.txt_peso_real.setText(_translate("Inicio", "2"))
        self.btn_calibrar.setText(_translate("Inicio", "CALIBRAR"))
        self.lbl_medio.setText(_translate("Inicio", "0"))
        self.lbltxtmargen_2.setText(_translate("Inicio", "ADC :"))
        self.lbltxDisplay_PesoReal.setText(_translate("Inicio", "Colocar Peso Real \n"
"en Kg"))
        self.btn_restart_adc.setText(_translate("Inicio", "REINICIAR ADC"))
        self.btn_mostrar_peso.setText(_translate("Inicio", "MOSTRAR EN KG"))
        self.lbl_port.setText(_translate("Inicio", "PUERTOS"))
        self.lbltxKG.setText(_translate("Inicio", "KG"))
